### ISSUE TITLE
Bulk mail support

### ISSUE THREAD

**Issue by shawnholt** [JMAConsulting/biz.jmaconsulting.mte#80]
@JoeMurray pls remove if this is not appropriate, but wanted to help the community get some clarity on current and planned bulk mail support.  In #76 there was reference to support for bounce processing in bulk mail in a version that needed testing.  Was that branch 1.5?  Are there plans to integrate enhancements for bulk mail?

I think that there is enough interest that we can get some contributors ($$$, code, testing) but would think we need to better understand current support, planed enhancements and feature requests.

I may have just convinced a client to migrate from icontact and civicrm 4.6 is focused on email enhancements so I'd like to strike while the iron is hot :)

**Comment by JoeMurray** [comment]
We received partial funding to integrate CiviMail with Mandrill. A fair degree of the delay on releasing this new version supporting bulk as well as transactional email has been this unfunded scope of about USD$3000. We have included additional automated tests for the extension particularly on the install process under Drupal, WordPress and Joomla!, since that was where the bulk of the support issues were.

The software for the extension is released under the AGPLv3 license. We have been providing free support as constrained by our availability for this pro bono work. We are very open to discussing a support model, such as a annual support plans common in the WordPress community, that would provide subscribers to those plans with a service level agreement including guaranteed response times for tickets.

We have been and intend to continue to support new versions of CiviCRM, and any changes to the Mandrill API.

We are interested in receiving feature requests, but implementing them is somewhat dependent on receiving funding.

Does this answer your questions? I'm happy to have a call to clarify if that would help.

**Comment by shawnholt** [comment]
Understood. Paid support sounds interesting for civicrm but does not sound right for just the module, however a MIH campaign to fund which includes support might be a different spin.  I know MIH have been controversial but could be a solution.  Also, www.bountysource.com is making some noise.  I believe there are others.  
Do you know if v. 1.5 supports webhook bounce processing from CiviMail?  That seems like it would be relatively easy if it doesn't (we are using SMTP for mandrill right now but bounce processing does not work.).  What other functionality did you have in mind.  If you have a spec/draft I'd be happy to contribute.  I can also try to do some fundraising in the community.  Thanks, Shawn

**Comment by herbdool** [comment]
I like the idea of using bountysource. We would be interested in encouraging some clients to help support this extension as well. My coworker mentioned to me that MIH is controversial if the funds aren't going to the core team, but perhaps a 10 to 20% buffer could be put into the cost to give to core if it requires integration, testing etc.

I think the bounce processing was the main thing that wasn't working yet with this extension.

**Comment by herbdool** [comment]
Now that version 2 supports CiviMail, I suppose this issue can be closed?
