### ISSUE TITLE
Set the SubAccount in emails

### ISSUE THREAD

**Issue by ixiam** [JMAConsulting/biz.jmaconsulting.mte#91]
Any plan on adding the feature to set the Mandrill's Subaccount when sending emails?

As far as I understood is just adding a SMTP header:
https://mandrill.zendesk.com/hc/en-us/articles/205582117-Using-SMTP-Headers-to-customize-your-messages#specify-the-subaccount-for-sending-the-message

**Comment by JoeMurray** [comment]
That seems like a good idea for hosting providers, but we haven't had a request for that until now. We'd accept a PR for it if you want to put it in.

**Comment by mlutfy** [comment]
SymbioTIC.coop has been testing this for a while and it seems to work well. I sent a PR:

https://github.com/JMAConsulting/biz.jmaconsulting.mte/pull/99

it was inspired from a patch found in CiviDesk's fork of the extension.

One mystery was how to configure Mandrill to send the webhook to the right instance, since you can't associate a webhook to the right subaccount. It just seems to work magically, but we have seen some errors that weren't too clear. Another option might be to proxy the webhook to a single host, filter from there and forward the request (but I haven't tried that yet).

**Comment by JoeMurray** [comment]
@mlutfy We are fixing some bugs related to creating multiple contacts, and also with regard to problems when a contact is not found on callback possibly due to deletion of contact, email, or mailing. Could you log errors on new release expected shortly on this subaccount stuff with details?
